# Generated by Django 5.2.16 on 2026-07-30 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Ambulance', 'Ambulance'), ('Bus', 'Bus'), ('Truck', 'Truck')], max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_contact', models.CharField(max_length=15)),
                ('destination_centre', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Available', max_length=50)),
                ('assigned_victim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='victims.victim')),
            ],
        ),
    ]
