# Generated by Django 5.2.16 on 2026-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('source_location', models.CharField(max_length=150)),
                ('current_location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Transport Assigned', 'Transport Assigned'), ('At Migration Centre', 'At Migration Centre'), ('Medical Check', 'Medical Check'), ('Shelter Allocated', 'Shelter Allocated'), ('Relief Provided', 'Relief Provided'), ('Safe', 'Safe')], default='Waiting', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
