# Generated by Django 5.2.16 on 2026-07-31 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_packets', models.PositiveIntegerField(default=0)),
                ('water_bottles', models.PositiveIntegerField(default=0)),
                ('medicine_kits', models.PositiveIntegerField(default=0)),
                ('blankets', models.PositiveIntegerField(default=0)),
                ('clothes', models.PositiveIntegerField(default=0)),
                ('distributed_by', models.CharField(max_length=100)),
                ('distribution_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Distributed', 'Distributed')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_records', to='victims.victim')),
            ],
        ),
    ]
