# Generated by Django 6.0.7 on 2026-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(max_length=20)),
                ('green_max', models.FloatField()),
                ('blue_max', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
    ]
