# Generated by Django 6.0.7 on 2026-07-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_map', '0002_hazardthreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('disaster_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('affected_regions', models.ManyToManyField(to='hazard_map.region')),
            ],
        ),
    ]
