# Generated by Django 6.0.7 on 2026-07-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_map', '0003_disasterevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(max_length=20)),
                ('value', models.FloatField()),
                ('zone_color', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disaster_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazard_map.disasterevent')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard_map.region')),
            ],
        ),
    ]
