# Generated by Django 6.0.7 on 2026-07-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_map', '0004_hazardreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_population', models.IntegerField()),
                ('source', models.CharField(default='census_2021', max_length=50)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hazard_map.region')),
            ],
        ),
        migrations.CreateModel(
            name='PopulationEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_population', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disaster_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazard_map.disasterevent')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard_map.region')),
            ],
        ),
    ]
