# Generated by Django 5.2.16 on 2026-07-31 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Waiting Rescue', 'Waiting Rescue'), ('Transport Assigned', 'Transport Assigned'), ('Medical Check', 'Medical Check'), ('Shelter Allocated', 'Shelter Allocated'), ('Relief Distributed', 'Relief Distributed'), ('Safe', 'Safe')], default='Waiting Rescue', max_length=50)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('victim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='victims.victim')),
            ],
        ),
    ]
