# Generated by Django 5.2.16 on 2026-07-31 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('capacity', models.PositiveIntegerField()),
                ('available_beds', models.PositiveIntegerField()),
                ('medical_facility', models.BooleanField(default=True)),
                ('food_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Full', 'Full')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_victim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='victims.victim')),
            ],
        ),
    ]
