# Generated by Django 5.2.16 on 2026-08-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='assigned_victim',
        ),
        migrations.CreateModel(
            name='ShelterAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('bed_number', models.CharField(max_length=50)),
                ('family_members', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Allocated', 'Allocated'), ('Pending Allocation', 'Pending Allocation'), ('Shifted', 'Shifted')], default='Pending Allocation', max_length=30)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='shelter.shelter')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_allocations', to='victims.victim')),
            ],
        ),
    ]
