# Generated by Django 5.2.16 on 2026-07-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_status', models.CharField(choices=[('No Injury', 'No Injury'), ('Minor Injury', 'Minor Injury'), ('Serious Injury', 'Serious Injury'), ('Critical', 'Critical')], max_length=50)),
                ('treatment_required', models.BooleanField(default=False)),
                ('medical_team', models.CharField(max_length=100)),
                ('current_health_status', models.CharField(choices=[('Stable', 'Stable'), ('Under Observation', 'Under Observation'), ('Under Treatment', 'Under Treatment'), ('Referred to Hospital', 'Referred to Hospital')], default='Stable', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victims.victim')),
            ],
        ),
    ]
