# Generated by Django 5.2.16 on 2026-07-31 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_level', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Critical', 'Critical')], max_length=20)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('pulse_rate', models.PositiveIntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('treatment', models.TextField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Treatment', 'Under Treatment'), ('Recovered', 'Recovered'), ('Referred', 'Referred')], default='Pending', max_length=30)),
                ('assessment_time', models.DateTimeField(auto_now_add=True)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='victims.victim')),
            ],
        ),
        migrations.DeleteModel(
            name='MedicalAssessment',
        ),
    ]
