# Generated by Django 5.2.16 on 2026-08-01 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('victims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_status', models.CharField(choices=[('Safe at Centre', 'Safe at Centre'), ('Under Treatment', 'Under Treatment'), ('Shifted', 'Shifted'), ('Reunited with Family', 'Reunited with Family')], default='Safe at Centre', max_length=50)),
                ('status_note', models.TextField(blank=True, null=True)),
                ('status_date', models.DateTimeField(auto_now=True)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_status_updates', to='victims.victim')),
            ],
        ),
    ]
